COMP003B.Assignment3/Models/Clothes.cs
using System.ComponentModel.DataAnnotations;

namespace COMP003B.Assignment3.Models
{
    public class Clothes
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Type { get; set; }

        [Required]
        public string Price { get; set; }    
    }
}

COMP003B.Assignment3/Models/ErrorViewModel.cs
namespace COMP003B.Assignment3.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

COMP003B.Assignment3/Controllers/ClothesController.cs
using COMP003B.Assignment3.Models;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment3.Controllers
{
	public class ClothesController : Controller
	{
		private static List <Clothes> _clothes = new List <Clothes> ();
        [HttpGet]
        public IActionResult Index()
		
		{
			return View(_clothes);
		}
        [HttpGet]
        public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Clothes clothes)
		{
			if (ModelState.IsValid)
			{
				if (!_clothes.Any(p=> p.Id ==clothes.Id))
				{
					_clothes.Add(clothes);
				}

				return RedirectToAction(nameof(Index));
			}
			return View();
		}
		[HttpGet]
        public IActionResult Edit(int? id) 
		{ 
			if(id == null)
			{
				return NotFound();
			}
			var clothes = _clothes.FirstOrDefault(p => p.Id == id);

			if (clothes == null)
			{
				return NotFound();
			}
			return View(clothes);
		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Clothes clothes) 
		{ 
			if (id != clothes.Id)
				{
					return NotFound();
				}
			if (ModelState.IsValid)
			{
				var existingClothes = _clothes.FirstOrDefault(p => p.Id == id);
				if(existingClothes!=null)
				{
					existingClothes.Type = clothes.Type;
					existingClothes.Price= clothes.Price;
				}
				return RedirectToAction(nameof(Index));
			}
			return View(clothes);
		}
		[HttpGet]
		public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var clothes = _clothes.FirstOrDefault(p => p.Id == id);

            if (clothes == null)
            {
                return NotFound();
            }
            return View(clothes);
        }
		[HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
		{
			var clothes = _clothes.FirstOrDefault(p => p.Id == id);
			if(clothes != null)
			{
				_clothes.Remove(clothes);
			}
			return RedirectToAction(nameof(Index));
		}
    }

}

COMP003B.Assignment3/Controllers/HomeController.cs
using COMP003B.Assignment3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace COMP003B.Assignment3.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

COMP003B.Assignment3/Views/Clothes/Create.cshtml
@model COMP003B.Assignment3.Models.Clothes

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Clothes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

COMP003B.Assignment3/Views/Clothes/Delete.cshtml
@model COMP003B.Assignment3.Models.Clothes

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Clothes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

COMP003B.Assignment3/Views/Clothes/Edit.cshtml
@model COMP003B.Assignment3.Models.Clothes

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Clothes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

COMP003B.Assignment3/Views/Clothes/Index.cshtml
@model IEnumerable<COMP003B.Assignment3.Models.Clothes>

@{
    ViewData["Title"] = "Index";
}

<h1>Indx</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                
                    @Html.ActionLink("Delete", "Delete", new {  id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

COMP003B.Assignment3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

COMP003B.Assignment3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COMP003B.Assignment3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/COMP003B.Assignment3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Clothes" asp-action="Index">COMP003B.Assignment3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clothes" asp-action="Index">Clothes</a>
                        </li>
             
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - COMP003B.Assignment3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>